package com.vaadin.samples.crud;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.flow.component.Tag;
import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.combobox.ComboBox;
import com.vaadin.flow.component.dependency.HtmlImport;
import com.vaadin.flow.component.polymertemplate.Id;
import com.vaadin.flow.component.polymertemplate.PolymerTemplate;
import com.vaadin.flow.component.textfield.TextField;
import com.vaadin.flow.templatemodel.TemplateModel;
import com.vaadin.samples.backend.data.Availability;

/**
 * !! DO NOT EDIT THIS FILE !!
 * <p>
 * This class is generated by Vaadin Designer and will be overwritten.
 * <p>
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
@HtmlImport("frontend://com/vaadin/samples/ProductFormDesign.html")
@Tag("product-form")
public class ProductFormDesign extends PolymerTemplate<TemplateModel> {
    @Id("productName")
    protected TextField productName;

    @Id("price")
    protected TextField price;

    @Id("stockCount")
    protected TextField stockCount;

    @Id("availability")
    protected ComboBox<Availability> availability;


    //TODO
    //protected CheckboxGroup<Category> category;

    @Id("save")
    protected Button save;

    @Id("discard")
    protected Button discard;

    @Id("cancel")
    protected Button cancel;

    @Id("delete")
    protected Button delete;

    public ProductFormDesign() {
        super();
    }
}